pipeline {
    agent any
    environment {
        PORT = '8080'
        EXTERNAL_PORT = '8510'
        DOCKER_TAG = 'thesis-api'
        PROVIDER_URL = credentials('THESIS_PROVIDER_URL')
        PRIVATE_KEY = credentials('THESIS_PRIVATE_KEY')
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'docker build -t $DOCKER_TAG .'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Stopping previous version...'
                sh 'docker stop $DOCKER_TAG || echo Nothing to stop'
                sh 'docker rm $DOCKER_TAG || echo Nothing to delete'
                echo 'Deploying....'
                sh 'docker run -d -e PORT -e PROVIDER_URL -e PRIVATE_KEY -e CONTRACT_ADDRESS -p $EXTERNAL_PORT:$PORT --name $DOCKER_TAG $DOCKER_TAG'
            }
        }
    }
}
