# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'es-AR'
early_access: false
reviews:
  profile: 'assertive'
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
    drafts: false
chat:
  auto_reply: true
knowledge_base:
  learnings:
    scope: 'global'
