import { ABI } from 'src/pkg/helpers/blockchainHelper';

export const CONTRACT_ABI: ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'batchId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'creator',
        type: 'address',
      },
    ],
    name: 'RecycledMaterialBatchCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'batchId',
        type: 'uint256',
      },
    ],
    name: 'RecycledMaterialBatchDeleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'batchId',
        type: 'uint256',
      },
    ],
    name: 'RecycledMaterialBatchUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bottleId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'WasteBottleCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bottleId',
        type: 'uint256',
      },
    ],
    name: 'WasteBottleDeleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'bottleId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'trackingCode',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'recycledBatchId',
        type: 'uint256',
      },
    ],
    name: 'WasteBottleUpdated',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'batchId', type: 'uint256' },
      { internalType: 'uint256', name: 'bottleId', type: 'uint256' },
    ],
    name: 'addWasteBottleToBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'contractOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'weight', type: 'uint256' },
      { internalType: 'string', name: 'size', type: 'string' },
      { internalType: 'string', name: 'materialType', type: 'string' },
      { internalType: 'string', name: 'composition', type: 'string' },
      { internalType: 'string', name: 'extraInfo', type: 'string' },
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'string', name: 'createdAt', type: 'string' },
    ],
    name: 'createRecycledMaterialBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'trackingCode', type: 'string' },
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'string', name: 'createdAt', type: 'string' },
    ],
    name: 'createWasteBottle',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'batchId', type: 'uint256' },
      { internalType: 'string', name: 'deletedAt', type: 'string' },
    ],
    name: 'deleteRecycledMaterialBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'bottleId', type: 'uint256' },
      { internalType: 'string', name: 'deletedAt', type: 'string' },
    ],
    name: 'deleteWasteBottle',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256[]', name: 'indexes', type: 'uint256[]' }],
    name: 'getRecycledMaterialBatchesList',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'uint256', name: 'weight', type: 'uint256' },
          { internalType: 'string', name: 'size', type: 'string' },
          { internalType: 'string', name: 'materialType', type: 'string' },
          { internalType: 'string', name: 'composition', type: 'string' },
          { internalType: 'string', name: 'extraInfo', type: 'string' },
          { internalType: 'address', name: 'buyerOwner', type: 'address' },
          { internalType: 'address', name: 'creator', type: 'address' },
          {
            internalType: 'uint256[]',
            name: 'wasteBottleIds',
            type: 'uint256[]',
          },
          { internalType: 'string', name: 'createdAt', type: 'string' },
          { internalType: 'string', name: 'deletedAt', type: 'string' },
        ],
        internalType: 'struct RecycledMaterialBatch[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'batchId', type: 'uint256' }],
    name: 'getWasteBottleIdsForBatch',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256[]', name: 'indexes', type: 'uint256[]' }],
    name: 'getWasteBottlesList',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'string', name: 'trackingCode', type: 'string' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'address', name: 'creator', type: 'address' },
          { internalType: 'uint256', name: 'recycledBatchId', type: 'uint256' },
          { internalType: 'string', name: 'createdAt', type: 'string' },
          { internalType: 'string', name: 'deletedAt', type: 'string' },
        ],
        internalType: 'struct WasteBottle[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextRecycledMaterialBatchId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextWasteBottleId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'baseBatchId', type: 'uint256' },
      { internalType: 'uint256', name: 'quantity', type: 'uint256' },
    ],
    name: 'recycleBaseBottles',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'recycledMaterials',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'uint256', name: 'weight', type: 'uint256' },
      { internalType: 'string', name: 'size', type: 'string' },
      { internalType: 'string', name: 'materialType', type: 'string' },
      { internalType: 'string', name: 'composition', type: 'string' },
      { internalType: 'string', name: 'extraInfo', type: 'string' },
      { internalType: 'address', name: 'buyerOwner', type: 'address' },
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'string', name: 'createdAt', type: 'string' },
      { internalType: 'string', name: 'deletedAt', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'batchId', type: 'uint256' },
      { internalType: 'uint256', name: 'bottleId', type: 'uint256' },
    ],
    name: 'removeWasteBottleFromBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'batchId', type: 'uint256' },
      { internalType: 'address', name: 'buyerOwner', type: 'address' },
    ],
    name: 'sellRecycledMaterialBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_baseBottlesBatchContract',
        type: 'address',
      },
    ],
    name: 'setBaseBottlesBatchContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_productBottlesBatchContract',
        type: 'address',
      },
    ],
    name: 'setProductBottlesBatchContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'batchId', type: 'uint256' },
      { internalType: 'uint256', name: 'weight', type: 'uint256' },
      { internalType: 'string', name: 'size', type: 'string' },
      { internalType: 'string', name: 'materialType', type: 'string' },
      { internalType: 'string', name: 'composition', type: 'string' },
      { internalType: 'string', name: 'extraInfo', type: 'string' },
    ],
    name: 'updateRecycledMaterialBatch',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'wasteBottles',
    outputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'string', name: 'trackingCode', type: 'string' },
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'uint256', name: 'recycledBatchId', type: 'uint256' },
      { internalType: 'string', name: 'createdAt', type: 'string' },
      { internalType: 'string', name: 'deletedAt', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
];
